### ISSUE TITLE
Can you please share the final .exe?

### ISSUE THREAD

**Issue by sven337** [0xmitsurugi/Analyzing-zip-file-with-.wsf-file-inside#1]
Hi,
I know it's malware and I'm not brave enough to run it, but I'm interested in disassembling it. Could you please share the final .exe? 
Thanks!

**Comment by 0xmitsurugi** [comment]
Clone the repo, then:

```
$ ./unxor.py o54b6
$ file o54b6-xored
o54b6-xored: PE32 executable (GUI) Intel 80386, for MS Windows
```

**Comment by sven337** [comment]
Stupid me. Thank you.
